
ALTER INDEX swarm_tracker_analyse_idx RENAME TO swarm_tracker_analyse_idx_old;
ALTER INDEX swarm_tracker_first_time_seen_idx RENAME TO swarm_tracker_first_time_seen_idx_old;
ALTER INDEX swarm_tracker_ip_and_time_range_idx RENAME TO swarm_tracker_ip_and_time_range_idx_old;
ALTER INDEX swarm_tracker_last_time_seen_idx RENAME TO swarm_tracker_last_time_seen_idx_old;
ALTER INDEX swarm_tracker_peer_client_name_idx RENAME TO swarm_tracker_peer_client_name_idx_old;
ALTER INDEX swarm_tracker_peer_client_name_trgm RENAME TO swarm_tracker_peer_client_name_trgm_old;
ALTER INDEX swarm_tracker_peer_geoip_idx RENAME TO swarm_tracker_peer_geoip_idx_old;
ALTER INDEX swarm_tracker_peer_ip_gist_idx RENAME TO swarm_tracker_peer_ip_gist_idx_old;
ALTER INDEX swarm_tracker_time_seen_idx RENAME TO swarm_tracker_time_seen_idx_old;
ALTER INDEX swarm_tracker_torrent_id_idx RENAME TO swarm_tracker_torrent_id_idx_old;
ALTER INDEX swarm_tracker_unique_idx RENAME TO swarm_tracker_unique_idx_old;
ALTER INDEX swarm_tracker_userapps_id_idx RENAME TO swarm_tracker_userapps_id_idx_old;
-- 1. 确保扩展存在
CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA public;
CREATE EXTENSION IF NOT EXISTS btree_gist SCHEMA public;

-- 2. 重命名旧表 (如果还没重命名)
ALTER TABLE "public"."swarm_tracker" RENAME TO "swarm_tracker_old";

-- 3. 创建新的分区主表 (主键名称改为 swarm_tracker_pk 以避开冲突)
CREATE TABLE "public"."swarm_tracker" (
                                          "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "userapps_id" int8,
                                          "user_downloader" varchar(255) NOT NULL,
                                          "torrent_id" int8 NOT NULL,
                                          "peer_ip" inet NOT NULL,
                                          "peer_port" int4 NOT NULL,
                                          "peer_id" varchar(20),
                                          "peer_client_name" text,
                                          "peer_progress" float8 NOT NULL,
                                          "from_peer_traffic" int8 NOT NULL,
                                          "to_peer_traffic" int8 NOT NULL,
                                          "from_peer_traffic_offset" int8 DEFAULT 0,
                                          "to_peer_traffic_offset" int8 DEFAULT 0,
                                          "flags" varchar(255),
                                          "first_time_seen" timestamptz(6) NOT NULL,
                                          "last_time_seen" timestamptz(6) NOT NULL,
                                          "user_progress" float8 NOT NULL,
                                          "peer_geoip" jsonb,
    -- 在创建表时直接定义主键，包含分区键
                                          CONSTRAINT "swarm_tracker_pk" PRIMARY KEY ("id", "last_time_seen")
) PARTITION BY RANGE (last_time_seen);

-- 4. 应用优化后的索引
CREATE INDEX "idx_st_ip_gist" ON "public"."swarm_tracker" USING gist ("peer_ip", "last_time_seen");
CREATE INDEX "idx_st_agg_cover" ON "public"."swarm_tracker" ("last_time_seen", "peer_ip", "torrent_id") INCLUDE ("from_peer_traffic", "to_peer_traffic");
CREATE INDEX "idx_st_userapps" ON "public"."swarm_tracker" ("userapps_id");

-- 5. 配置 pg_partman 自动化管理
-- 这会自动创建当前和未来的分区表
SELECT public.create_parent(
               p_parent_table := 'public.swarm_tracker',
               p_control := 'last_time_seen',
               p_interval := '1 day',
               p_premake := 7
       );

-- 设置保留策略：保留 7 天，自动删除旧表
UPDATE public.part_config
SET retention = '7 days',
    retention_keep_table = false
WHERE parent_table = 'public.swarm_tracker';