/*
 Navicat Premium Dump SQL

 Source Server         : sparkle3
 Source Server Type    : PostgreSQL
 Source Server Version : 170007 (170007)
 Source Host           : cyrene:5433
 Source Catalog        : sparkle
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170007 (170007)
 File Encoding         : 65001

 Date: 23/12/2025 18:59:19
*/


-- ----------------------------
-- Table structure for ipdb_measure
-- ----------------------------
DROP TABLE IF EXISTS "public"."ipdb_measure";
CREATE TABLE "public"."ipdb_measure" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "ip" inet NOT NULL,
  "measure_id" varchar(255) COLLATE "pg_catalog"."default",
  "measure_at" timestamptz(6),
  "measure_success" bool,
  "result" jsonb,
  "belong_cidr" inet NOT NULL
)
;

-- ----------------------------
-- Indexes structure for table ipdb_measure
-- ----------------------------
CREATE INDEX "ipdb_measure_belong_cidr" ON "public"."ipdb_measure" USING btree (
  "ip" "pg_catalog"."inet_ops" ASC NULLS LAST
);
CREATE INDEX "ipdb_measure_ip" ON "public"."ipdb_measure" USING btree (
  "ip" "pg_catalog"."inet_ops" ASC NULLS LAST
);
CREATE INDEX "ipdb_measure_measure_at" ON "public"."ipdb_measure" USING btree (
  "measure_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
);
CREATE INDEX "ipdb_measure_query" ON "public"."ipdb_measure" USING btree (
  "belong_cidr" "pg_catalog"."inet_ops" ASC NULLS LAST,
  "measure_at" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST,
  "measure_success" "pg_catalog"."bool_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "ipdb_measure_unique" ON "public"."ipdb_measure" USING btree (
  "ip" "pg_catalog"."inet_ops" ASC NULLS LAST,
  "measure_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table ipdb_measure
-- ----------------------------
ALTER TABLE "public"."ipdb_measure" ADD CONSTRAINT "ipdb_measure_pkey" PRIMARY KEY ("id");
