ALTER TABLE "public"."ban_history" RENAME TO "ban_history_old";
ALTER INDEX "public"."banhistory_pkey" RENAME TO "banhistory_pkey_old";
ALTER INDEX "ban_history_analyse_idx" RENAME TO "ban_history_analyse_idx_old";
ALTER INDEX "ban_history_description_trgm" RENAME TO "ban_history_description_trgm_old";
ALTER INDEX "ban_history_insert_time_idx" RENAME TO "ban_history_insert_time_idx_old";
ALTER INDEX "ban_history_modulename_idx" RENAME TO "ban_history_modulename_idx_old";
ALTER INDEX "ban_history_peer_client_name_idx" RENAME TO "ban_history_peer_client_name_idx_old";
ALTER INDEX "ban_history_peer_client_name_trgm" RENAME TO "ban_history_peer_client_name_trgm_old";
ALTER INDEX "ban_history_peer_flags_idx" RENAME TO "ban_history_peer_flags_idx_old";
ALTER INDEX "ban_history_peer_geoip_idx" RENAME TO "ban_history_peer_geoip_idx_old";
ALTER INDEX "ban_history_peer_id_idx" RENAME TO "ban_history_peer_id_idx_old";
ALTER INDEX "ban_history_peer_ip_idx" RENAME TO "ban_history_peer_ip_idx_old";
ALTER INDEX "ban_history_populate_time_idx" RENAME TO "ban_history_populate_time_idx_old";
ALTER INDEX "ban_history_structured_data" RENAME TO "ban_history_structured_data_old";
ALTER INDEX "ban_history_torrent_id_idx" RENAME TO "ban_history_torrent_id_idx_old";
ALTER INDEX "ban_history_userapps_idx" RENAME TO "ban_history_userapps_idx_old";
CREATE TABLE "public"."ban_history" (
                                        "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
                                            ),
                                        "insert_time" timestamptz(6) NOT NULL,
                                        "populate_time" timestamptz(6) NOT NULL,
                                        "userapps_id" int8 NOT NULL,
                                        "torrent_id" int8 NOT NULL,
                                        "peer_ip" inet NOT NULL,
                                        "peer_port" int4 NOT NULL,
                                        "peer_id" varchar(20) COLLATE "pg_catalog"."default",
                                        "peer_client_name" text COLLATE "pg_catalog"."default",
                                        "peer_progress" float8 NOT NULL,
                                        "peer_flags" varchar(255) COLLATE "pg_catalog"."default",
                                        "peer_geoip" jsonb,
                                        "reporter_progress" float8,
                                        "to_peer_traffic" int8 NOT NULL,
                                        "from_peer_traffic" int8 NOT NULL,
                                        "module_name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
                                        "rule" text COLLATE "pg_catalog"."default" NOT NULL,
                                        "structured_data" jsonb,
                                        "description" text COLLATE "pg_catalog"."default",
                                        CONSTRAINT "banhistory_pkey" PRIMARY KEY ("id", "populate_time")
) PARTITION BY RANGE ("populate_time");

-- 4. 在父表上重新创建所有索引
-- PostgreSQL 会自动将这些索引应用到未来的子分区上
CREATE INDEX "ban_history_analyse_idx" ON "public"."ban_history" USING btree (
                                                                              "insert_time" "pg_catalog"."timestamptz_ops" ASC NULLS LAST,
                                                                              "peer_ip" "pg_catalog"."inet_ops" ASC NULLS LAST,
                                                                              "peer_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
                                                                              "peer_client_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_description_trgm" ON "public"."ban_history" USING gin (
                                                                                 "description" COLLATE "pg_catalog"."default" "public"."gin_trgm_ops"
    );
CREATE INDEX "ban_history_insert_time_idx" ON "public"."ban_history" USING btree (
                                                                                  "insert_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
    );
CREATE INDEX "ban_history_modulename_idx" ON "public"."ban_history" USING btree (
                                                                                 "module_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_peer_client_name_idx" ON "public"."ban_history" USING btree (
                                                                                       "peer_client_name" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_peer_client_name_trgm" ON "public"."ban_history" USING gin (
                                                                                      "peer_client_name" COLLATE "pg_catalog"."default" "public"."gin_trgm_ops"
    );
CREATE INDEX "ban_history_peer_flags_idx" ON "public"."ban_history" USING btree (
                                                                                 "peer_flags" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_peer_geoip_idx" ON "public"."ban_history" USING gin (
                                                                               "peer_geoip" "pg_catalog"."jsonb_ops"
    ) WITH (GIN_PENDING_LIST_LIMIT = 4096);
CREATE INDEX "ban_history_peer_id_idx" ON "public"."ban_history" USING btree (
                                                                              "peer_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_peer_ip_idx" ON "public"."ban_history" USING gist (
                                                                             "peer_ip" "pg_catalog"."inet_ops"
    );
CREATE INDEX "ban_history_populate_time_idx" ON "public"."ban_history" USING btree (
                                                                                    "populate_time" "pg_catalog"."timestamptz_ops" DESC NULLS FIRST
    );
CREATE INDEX "ban_history_structured_data" ON "public"."ban_history" USING gin (
                                                                                "structured_data" "pg_catalog"."jsonb_ops"
    ) WITH (GIN_PENDING_LIST_LIMIT = 4096);
CREATE INDEX "ban_history_torrent_id_idx" ON "public"."ban_history" USING btree (
                                                                                 "torrent_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );
CREATE INDEX "ban_history_userapps_idx" ON "public"."ban_history" USING btree (
                                                                               "userapps_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );

SELECT create_parent(
               p_parent_table => 'public.ban_history',
               p_control => 'populate_time',
               p_interval => '1 month',
               p_premake => 1,
               p_start_partition => (SELECT min(populate_time)::text FROM ban_history_old)
       );
INSERT INTO "public"."ban_history"
SELECT * FROM "public"."ban_history_old"
ON CONFLICT DO NOTHING;